import { describe, it, before } from "node:test";
import assert from "node:assert/strict";
import { network } from "hardhat";
import { readFileSync } from "node:fs";

/**
 * BinaryPricer is validated against scipy.stats.norm.
 *
 * The golden vectors in test/vectors/binary_pricer.json are generated by
 * reference/pricer_reference.py. If the Solidity and SciPy disagree beyond
 * tolerance, the Solidity is wrong -- SciPy is the source of truth here.
 */
const vectors = JSON.parse(
  readFileSync(new URL("./vectors/binary_pricer.json", import.meta.url), "utf8"),
) as {
  pricer: Array<{ spot: string; strike: string; sigma: string; tau: string; d2: string; prob: string; _note: string }>;
  phi: Array<{ x: string; cdf: string }>;
  econ: Array<{ prob: string; price: string; edgeBps: string; breakEvenBps: string; kelly: string }>;
};

const WAD = 10n ** 18n;
const TERMINAL = 0;
const AVERAGE = 1;

/** A&S 26.2.17 has |error| < 7.5e-8; allow 1e-7 in WAD terms. */
const PHI_TOLERANCE = 100_000_000_000n;
/** Fixed-point error accumulates through ln, sqrt, exp; 1e-6 is still 4 orders below a basis point. */
const PROB_TOLERANCE = 1_000_000_000_000n;

const wad = (n: number) => BigInt(Math.round(n * 1e18));
const absDiff = (a: bigint, b: bigint) => (a > b ? a - b : b - a);

describe("BinaryPricer", () => {
  let h: any;

  before(async () => {
    const { viem } = await network.connect();
    h = await viem.deployContract("BinaryPricerHarness");
  });

  describe("normalCdf — validated against scipy.stats.norm", () => {
    for (const v of vectors.phi) {
      it(`Phi(${(Number(v.x) / 1e18).toFixed(1)})`, async () => {
        const got: bigint = await h.read.normalCdf([BigInt(v.x)]);
        const want = BigInt(v.cdf);
        const diff = absDiff(got, want);
        assert.ok(
          diff <= PHI_TOLERANCE,
          `x=${v.x}\n  got  ${got}\n  want ${want}\n  diff ${diff} > ${PHI_TOLERANCE}`,
        );
      });
    }

    it("Phi(0) is exactly one half", async () => {
      const got: bigint = await h.read.normalCdf([0n]);
      assert.ok(absDiff(got, WAD / 2n) <= PHI_TOLERANCE, `got ${got}`);
    });

    it("is symmetric: Phi(-x) == 1 - Phi(x)", async () => {
      for (const x of [wad(0.3), wad(1.1), wad(2.4)]) {
        const pos: bigint = await h.read.normalCdf([x]);
        const neg: bigint = await h.read.normalCdf([-x]);
        assert.ok(absDiff(pos + neg, WAD) <= PHI_TOLERANCE, `x=${x} pos=${pos} neg=${neg}`);
      }
    });

    it("is monotonically increasing", async () => {
      let prev = -1n;
      for (const x of [wad(-3), wad(-1), wad(-0.2), 0n, wad(0.2), wad(1), wad(3)]) {
        const got: bigint = await h.read.normalCdf([x]);
        assert.ok(got > prev, `not increasing at x=${x}: ${got} <= ${prev}`);
        prev = got;
      }
    });

    it("stays within [0, 1] in the far tails", async () => {
      assert.ok((await h.read.normalCdf([wad(-40)])) <= WAD);
      assert.ok((await h.read.normalCdf([wad(40)])) <= WAD);
    });
  });

  describe("probUp — validated against scipy", () => {
    for (const v of vectors.pricer) {
      it(v._note, async () => {
        const got: bigint = await h.read.probUp([
          BigInt(v.spot), BigInt(v.strike), BigInt(v.sigma), BigInt(v.tau), TERMINAL,
        ]);
        const want = BigInt(v.prob);
        const diff = absDiff(got, want);
        assert.ok(
          diff <= PROB_TOLERANCE,
          `${v._note}\n  got  ${got}\n  want ${want}\n  diff ${diff} > ${PROB_TOLERANCE}`,
        );
      });
    }
  });

  describe("probUp — behaviour that defines the instrument", () => {
    const S = 100_000n * WAD;
    const sigma = wad(0.01);

    it("is a coin flip at the money with a full window (strike == opening price)", async () => {
      const p: bigint = await h.read.probUp([S, S, sigma, WAD, TERMINAL]);
      // Exactly Phi(-sigma/2), just under 0.5. This is why fair value is
      // uninformative at open and only becomes interesting mid-window.
      assert.ok(p > wad(0.49) && p < wad(0.50), `expected just under 0.5, got ${p}`);
    });

    it("decreases monotonically as the strike rises", async () => {
      const low: bigint = await h.read.probUp([S, 99_000n * WAD, sigma, WAD, TERMINAL]);
      const mid: bigint = await h.read.probUp([S, 100_000n * WAD, sigma, WAD, TERMINAL]);
      const high: bigint = await h.read.probUp([S, 101_000n * WAD, sigma, WAD, TERMINAL]);
      assert.ok(low > mid && mid > high, `${low} > ${mid} > ${high}`);
    });

    it("sharpens toward certainty as time runs out — the core effect", async () => {
      // Spot 0.3% above the opening line. The SAME move means something very
      // different with the whole window left versus moments before expiry.
      const spot = 100_300n * WAD;
      const full: bigint = await h.read.probUp([spot, S, sigma, WAD, TERMINAL]);
      const late: bigint = await h.read.probUp([spot, S, sigma, wad(0.1), TERMINAL]);
      assert.ok(late > full, `late ${late} should exceed full-window ${full}`);
      assert.ok(late > wad(0.80), `expected strongly convinced near expiry, got ${late}`);
    });

    it("is symmetric for equal moves above and below the line", async () => {
      const up: bigint = await h.read.probUp([100_300n * WAD, S, sigma, wad(0.1), TERMINAL]);
      const down: bigint = await h.read.probUp([99_700n * WAD, S, sigma, wad(0.1), TERMINAL]);
      // Not exactly 1 -- the -sigma^2*tau/2 drift term breaks perfect symmetry.
      assert.ok(absDiff(up + down, WAD) < wad(0.01), `up=${up} down=${down}`);
    });

    it("is less certain when volatility is higher", async () => {
      const spot = 100_300n * WAD;
      const calm: bigint = await h.read.probUp([spot, S, wad(0.005), wad(0.2), TERMINAL]);
      const wild: bigint = await h.read.probUp([spot, S, wad(0.05), wad(0.2), TERMINAL]);
      assert.ok(calm > wild, `calm ${calm} should exceed volatile ${wild}`);
    });

    it("prices average settlement differently from terminal settlement", async () => {
      const args = [100_500n * WAD, S, sigma, WAD] as const;
      const terminal: bigint = await h.read.probUp([...args, TERMINAL]);
      const average: bigint = await h.read.probUp([...args, AVERAGE]);
      assert.notEqual(terminal, average);
    });

    it("rejects zero volatility", async () => {
      await assert.rejects(() => h.read.probUp([S, S, 0n, WAD, TERMINAL]));
    });

    it("rejects zero time remaining", async () => {
      await assert.rejects(() => h.read.probUp([S, S, sigma, 0n, TERMINAL]));
    });

    it("rejects a zero price", async () => {
      await assert.rejects(() => h.read.probUp([0n, S, sigma, WAD, TERMINAL]));
      await assert.rejects(() => h.read.probUp([S, 0n, sigma, WAD, TERMINAL]));
    });
  });

  describe("economics — validated against the reference", () => {
    for (const v of vectors.econ) {
      const p = Number(v.prob) / 1e18;
      const a = Number(v.price) / 1e18;

      it(`edge at p=${p.toFixed(2)} price=${a.toFixed(2)}`, async () => {
        const got: bigint = await h.read.edgeBps([BigInt(v.prob), BigInt(v.price)]);
        assert.equal(got, BigInt(v.edgeBps));
      });

      it(`break-even at price=${a.toFixed(2)}`, async () => {
        const got: bigint = await h.read.breakEvenWinRateBps([BigInt(v.price)]);
        assert.equal(got, BigInt(v.breakEvenBps));
      });

      it(`kelly at p=${p.toFixed(2)} price=${a.toFixed(2)}`, async () => {
        const got: bigint = await h.read.kellyFractionWad([BigInt(v.prob), BigInt(v.price)]);
        const want = BigInt(v.kelly);
        assert.ok(absDiff(got, want) <= PROB_TOLERANCE, `got ${got} want ${want}`);
      });
    }

    it("break-even win rate IS the price — the fact nobody tells traders", async () => {
      assert.equal(await h.read.breakEvenWinRateBps([wad(0.7)]), 7000n);
    });

    it("edge is zero at fair value", async () => {
      assert.equal(await h.read.edgeBps([wad(0.5), wad(0.5)]), 0n);
    });

    it("edge is negative when the book is above the model", async () => {
      assert.equal(await h.read.edgeBps([wad(0.4), wad(0.55)]), -1500n);
    });

    it("kelly is zero without a positive edge", async () => {
      assert.equal(await h.read.kellyFractionWad([wad(0.5), wad(0.5)]), 0n);
      assert.equal(await h.read.kellyFractionWad([wad(0.4), wad(0.6)]), 0n);
    });

    it("kelly never exceeds the whole bankroll", async () => {
      assert.ok((await h.read.kellyFractionWad([wad(0.999), wad(0.001)])) <= WAD);
    });

    it("rejects prices outside (0,1) — a binary price is a probability", async () => {
      await assert.rejects(() => h.read.edgeBps([wad(0.5), 0n]));
      await assert.rejects(() => h.read.edgeBps([wad(0.5), WAD]));
      await assert.rejects(() => h.read.breakEvenWinRateBps([WAD]));
      await assert.rejects(() => h.read.kellyFractionWad([wad(0.5), 0n]));
    });
  });

  describe("the demo scenario, end to end", () => {
    it("finds ~1278 bps of edge on a 0.3% move near expiry priced at 0.70", async () => {
      // A 0.3% move on BTC is noise. With 10% of the window left it is not.
      const spot = 100_300n * WAD;
      const strike = 100_000n * WAD;
      const p: bigint = await h.read.probUp([spot, strike, wad(0.01), wad(0.1), TERMINAL]);
      const book = wad(0.70);

      const edge: bigint = await h.read.edgeBps([p, book]);
      const breakEven: bigint = await h.read.breakEvenWinRateBps([book]);
      const kelly: bigint = await h.read.kellyFractionWad([p, book]);

      assert.ok(p > wad(0.82) && p < wad(0.84), `fair probability ${p}`);
      assert.ok(edge > 1200n && edge < 1350n, `edge ${edge} bps`);
      assert.equal(breakEven, 7000n);
      assert.ok(kelly > 0n, "a positive edge must produce a positive Kelly stake");
    });
  });
});
