// Validates this backtest's pricer.mjs against the SAME golden vectors the
// Solidity BinaryPricer is tested against (test/vectors/binary_pricer.json,
// generated by reference/pricer_reference.py from scipy.stats.norm). Three
// independent implementations (Solidity, this JS port, the Python reference)
// agreeing on one vector set is the strongest correctness claim available.
import { readFileSync } from "node:fs";
import { normalCdf, probUp, edgeBps, breakEvenBps, kellyFraction } from "./pricer.mjs";

const WAD = 1e18;
const fromWad = (s) => Number(BigInt(s)) / WAD;

const vectors = JSON.parse(readFileSync(new URL("../test/vectors/binary_pricer.json", import.meta.url)));

let maxErr = 0, fails = 0, total = 0;
function check(label, got, want, tol) {
  total++;
  const err = Math.abs(got - want);
  maxErr = Math.max(maxErr, err);
  if (err > tol) { fails++; console.log(`FAIL ${label}: got ${got} want ${want} err ${err}`); }
}

for (const v of vectors.phi) {
  check(`phi(${fromWad(v.x)})`, normalCdf(fromWad(v.x)), fromWad(v.cdf), 2e-6);
}
for (const v of vectors.pricer) {
  const got = probUp(fromWad(v.spot), fromWad(v.strike), fromWad(v.sigma), fromWad(v.tau));
  check(v._note, got, fromWad(v.prob), 2e-6);
}
for (const v of vectors.econ) {
  const p = fromWad(v.prob), a = fromWad(v.price);
  check(`edgeBps(${p},${a})`, edgeBps(p, a), Number(v.edgeBps), 0.05);
  check(`breakEvenBps(${a})`, breakEvenBps(a), Number(v.breakEvenBps), 0.05);
  check(`kelly(${p},${a})`, kellyFraction(p, a), fromWad(v.kelly), 2e-6);
}

console.log(`\n${total - fails}/${total} vectors matched within tolerance. Max abs error: ${maxErr.toExponential(3)}`);
if (fails > 0) { console.log(`${fails} FAILURES`); process.exit(1); }
console.log("PASS — TS port agrees with the SciPy reference across phi/pricer/econ vectors.");
